name: ocicl CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        implementation: ['sbcl'] # ['abcl', 'clisp', 'ecl', 'sbcl']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: '${{ matrix.os }}'
    name: 'Install Common Lisp'
    defaults:
      run:
        shell: bash
    steps:

    - uses: actions/checkout@v4

    - name: Install deps (MacOS via Homebrew)
      if: runner.os == 'macos'
      run: |
        brew install sbcl ocicl
        # expose brew env to later steps
        brew shellenv | sed 's/^export //' >> "$GITHUB_ENV"
        echo "$(brew --prefix)/bin" >> "$GITHUB_PATH"
        echo "$(brew --prefix)/sbin" >> "$GITHUB_PATH"

    - name: Install deps (Linux via Homebrew)
      if: runner.os == 'Linux'
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install sbcl ocicl
        # expose brew env to later steps
        brew shellenv | sed 's/^export //' >> "$GITHUB_ENV"
        echo "$(brew --prefix)/bin" >> "$GITHUB_PATH"
        echo "$(brew --prefix)/sbin" >> "$GITHUB_PATH"

    - name: Install deps (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        choco install -y sbcl openssl.light
        echo "C:\Program Files\OpenSSL\bin" | Out-File $env:GITHUB_PATH -Append
        # OCICL (Download from GitHub Releases)
        $version = "2.20.0"
        $url = "https://github.com/ocicl/ocicl/releases/download/v$version/ocicl-$version-windows-amd64.zip"
        $installDir = "$env:RUNNER_TEMP\ocicl"

        New-Item -ItemType Directory -Force -Path $installDir | Out-Null

        Invoke-WebRequest `
          -Uri $url `
          -OutFile "$env:RUNNER_TEMP\ocicl.zip"

        Expand-Archive `
          -Path "$env:RUNNER_TEMP\ocicl.zip" `
          -DestinationPath $installDir `
          -Force

        # Make ocicl available to subsequent GitHub Actions steps
        Add-Content -Path $env:GITHUB_PATH -Value $installDir


    - name: Install OCICL dependencies and build
      run: |
        ocicl setup
        ocicl install
        ./build.sh

    - name: Run Tests
      run: ./test.sh
